<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modulos/ModuloEstoque/Apresentacao/Views/" />
    <Folder Include="Modulos/ModuloFuncionario/" />
    <Folder Include="Modulos/ModuloFuncionario/Aplicacao/" />
    <Folder Include="Modulos/ModuloFuncionario/Apresentacao/" />
    <Folder Include="Modulos/ModuloFuncionario/Apresentacao/Views/" />
    <Folder Include="Modulos/ModuloFuncionario/Dominio/" />
    <Folder Include="Modulos/ModuloFuncionario/Infra/" />
    <Folder Include="Modulos/ModuloPaciente/Aplicacao/" />
    <Folder Include="Modulos/ModuloPaciente/Apresentacao/" />
    <Folder Include="Modulos/ModuloPaciente/Apresentacao/Views/" />
    <Folder Include="Modulos/ModuloPaciente/Infra/" />
    <Folder Include="Modulos\ModuloFornecedor\" />
    <Folder Include="Modulos\ModuloMedicamento\" />
    <Folder Include="wwwroot/" />
    <Folder Include="wwwroot/css/" />
    <Folder Include="wwwroot/img/" />
  </ItemGroup>

</Project>
